[debug]
address = "0.0.0.0"
port = 8080
workers = 4
log_level = "normal"
limits = { forms = 32768 }


[release]
address = "0.0.0.0"
port = 82
workers = 4
log_level = "critical"
limits = { forms = 32768 }
