[debug]
address = "0.0.0.0"
port = 8080
workers = 4
log_level = "normal"


[release]
address = "0.0.0.0"
port = 7000
workers = 4
log_level = "critical"


[default.limits]
data-form="10 GiB"
file="10 GiB"